import SETheoryTransformation.Basic
import SETheoryTransformation.TransformationClass
import SETheoryTransformation.Operator
import SETheoryTransformation.Family
import SETheoryTransformation.Composition
import SETheoryTransformation.Outcome
import SETheoryTransformation.Orthogonality
import SETheoryTransformation.Registry

import SETheoryTransformation.Transformation.Primitive
import SETheoryTransformation.Transformation.Structural
import SETheoryTransformation.Transformation.Temporal
import SETheoryTransformation.Transformation.Contextual
import SETheoryTransformation.Transformation.Normative
import SETheoryTransformation.Transformation.Observational

import SETheoryTransformation.Operator.Codes
import SETheoryTransformation.Operator.Semantics
import SETheoryTransformation.Operator.Admissibility

import SETheoryTransformation.Family.Branching
import SETheoryTransformation.Family.Decomposition
import SETheoryTransformation.Family.Aggregation
import SETheoryTransformation.Family.Projection
import SETheoryTransformation.Family.Reorganization
import SETheoryTransformation.Family.Versioning
import SETheoryTransformation.Family.Migration


/-!
# SETheoryTransformation

Public import surface for `se-theory-transformation`.

This module re-exports the foundational transformation theory surface.
It defines no additional semantics.
-/
